services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=YourPassword123!
      - MYSQL_DATABASE=scores_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure

  migrations:
    build: ./db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=YourPassword123!
      - DATABASE_NAME=scores_db
    depends_on:
      - db
    restart: always